# Generated by Django 4.0.1 on 2022-01-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
